---
- hosts: testservers
#  become: yes
  tasks:
  - name: job
    jenkins_job:
      config: "{{ lookup('file', 'job.xml') }}"
      #enabled: yes
      name: test
      state: present
      token: 780b7e3c78e5014a1372abdd9eb1b4cb
      url: http://192.168.11.109:8080
      user: polyglot
      #password: default123

