---
- hosts: 192.168.2.21
  become: yes
  tasks:
  - name: stop tomcat
    service: name=tomcat state=stopped

  - name: downloading and deploying from nexus
    maven_artifact: group_id=com.polyglot artifact_id=Tadaay repository_url=http://192.168.11.109:8081/nexus/content/repositories/tadaay_qa/ username=polyglot password=default123 dest=/opt/tomcat/webapps/ROOT.war version=latest extension=war  

  - name: restart tomcat
    service: name=tomcat state=restarted 
